### ISSUE TITLE
Fix last bugs for FLSR proper deployment

### ISSUE THREAD

**Issue by dd84ai** [darklab8/fl-darkstat#67]
- [x] base tab should not be having Price to Buy and to Sell. show only single Price
- [x] Your vanilla deployment became crashing after FLSR changes. (issues with 1e+30 are fixed)
- [x] Show cruise speed for FLSR Ships tab just in case too. Not vanilla stuff
- [x] remove Ship Class showing in regular tabs. it is disco specific thing
- [x] Add proper Workflow trigger for redeployment of FLSR automatically
- [x] Write README.md for repo fl-data-flsr (and LICENSE i guess too)
- [x] may be not showing Burst (Catridges) column names for not Discos too
- [x] Fix anchor link to the blog section as more generic freelancer named
- [x] also problems with parser improvements https://github.com/darklab8/fl-configs/pull/18
- [x] investigate strange NaN showing routes in Trade tabs
- Fix filtering mechanism for Guns and other tabs, show next ones by default
  - [x] lootable
  - [x] crafting recipes https://github.com/Freelancer-Sirius-Revival/FLSR/blob/f61449382fcb52f85635019c28223550b74ecc2f/FLHook/2.0/plugins/flsr_plugin/configs/FLSR-Crafting.cfg#L427
  - or inbuilt into ship during buying (i think they aren't important to show)

Check for whatever else u will discover

**Comment by Caenen** [comment]
- [ ] Mass is an important stat for all equipment and cargo in FL:SR, as it adds directly to your ship mass (adoxa plugin). Mines also use it in their acceleration formula, even in Vanilla so that may be a generally good thing to add for them.
- [ ] FL:SR uses a net of proxy systems with (from the outside) inaccessible jump holes to connect all systems. This net is interpreted like any other set of connections by darkstat, and thus all the travel times and trade route speeds look rather quick.
- [ ] It should be possible to generate AverageTradeLaneSpeed dynamically out of a target mod's data. On FL:SR the trade lane speed is set to 5000, so X-250 may be a decent shorthand still.

**Comment by dd84ai** [comment]
@Caenen on the topic of average trade lane speed. For now added as
```go
	if configs.FLSR != nil {
		// make this value part of config files some day
		average_trade_lane_speed = 5000
	}
```
if flsr then hardcoded like this fow now, but best if this value will be present somewhere for reading indeed.
I propose perhaps for readability purposes adding file may be..
DATA/darklab.ini file i guess?
```go
[FlConfigs]
AVERAGE_TRADE_LANE_SPEED = 5000
```
(I don't see this value accessable in any other way)

**Comment by Caenen** [comment]
In the FL:SR repo, we're using a patcher tool to conveniently apply AND document our binary changes.

The trade lane speed in our case can simply be read out of the common.dll.patch file: https://github.com/Freelancer-Sirius-Revival/FLSR/blob/71771477b902d9b97b5510f5867fb88127fb6ecb/BinaryPatches/EXE/common.dll.patch#L72

Different mods will have different solutions here, of course. Might as well be hardcoded or manually adjustable on the front-end. For comparison with likeminded software, FLCompanion just lets you select the trade lane speed esimate you want to use in the settings menu.

**Comment by dd84ai** [comment]
Well, if it is in text, i guess i could read it. The file format is very different from ini though
